# ReplicaSet simple avec 3 replicas nginx

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    tier: frontend
spec:
  # Nombre de replicas désirées
  replicas: 3

  # Selector pour identifier les Pods gérés
  selector:
    matchLabels:
      app: nginx

  # Template des Pods à créer
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
