# Replication Controller (ancien - ne plus utiliser)
# Fourni uniquement pour comparaison avec ReplicaSet

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  # Nombre de replicas
  replicas: 3

  # Selector simple (égalité uniquement)
  selector:
    app: nginx

  # Template des Pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80

# ⚠️ ATTENTION : Replication Controller est déprécié !
# Utilisez ReplicaSet à la place (ou mieux : Deployment)
